#!/bin/bash

if [ $EUID == 0 ]; then
	echo "This script must not be run as root"
	exit
fi

DATA_PATH="/opt/cathook"

echo "Installing additional cathook files"


if ! [ -e "$DATA_PATH" ]
then
	echo "Making cathook data folder at $DATA_PATH"
	sudo mkdir -p "$DATA_PATH"
	sudo chown $USER:$USER "$DATA_PATH"
fi

rsync -avh --progress "data/" "$DATA_PATH"